#version: '3.8'

services:
  roast-backend:
    build: .
    container_name: roast-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
